apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  labels:
    app: SERVICE_NAME
    service: SERVICE_NAME
    group: SERVICE_GROUP
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: SERVICE_NAME
    group: SERVICE_GROUP

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: SERVICE_NAME
spec:
  hosts:
    - "*"
  gateways:
    - nara-gateway
  http:
    - match:
        - uri:
            prefix: /api/SERVICE_NAME/
      rewrite:
        uri: /
      route:
        - destination:
            host: SERVICE_NAME
            port:
              number: 8080
